<?php
declare(strict_types=1);

return [
    'app' => [
        'base_url' => 'https://a1technovation.com',
        'contact_page' => '/pages/contact',
        'timezone' => 'Asia/Dhaka',
    ],
    'database' => [
        'enabled' => false,
        'host' => '127.0.0.1',
        'port' => 3306,
        'name' => 'a1technovation',
        'username' => 'db_user',
        'password' => 'change-me',
    ],
    'smtp' => [
        'host' => 'smtp.gmail.com',
        'port' => 587,
        'username' => 'smtp-user@example.com',
        'password' => 'app-password',
        'encryption' => 'tls',
        'auth' => true,
        'timeout' => 20,
        'helo_host' => 'a1technovation.com',
    ],
    'mail' => [
        'from_email' => 'noreply@a1technovation.com',
        'from_name' => 'A1 Technovation',
        'notification_email' => 'info.a1technovation@gmail.com',
        'notification_name' => 'A1 Technovation Sales',
        'transport' => 'smtp',
        'fallback_to_native_mail' => true,
        'send_auto_reply' => true,
        'auto_reply_subject' => 'Thanks for contacting A1 Technovation',
    ],
    'captcha' => [
        'enabled' => true,
        'ttl_seconds' => 900,
        'min_number' => 2,
        'max_number' => 12,
    ],
    'anti_spam' => [
        'enabled' => true,
        'require_same_site' => true,
        'minimum_submit_seconds' => 4,
        'max_links_in_message' => 2,
        'check_email_dns' => true,
        'check_website_dns' => true,
        'rate_limit_window_seconds' => 900,
        'max_submissions_per_ip' => 3,
        'max_submissions_per_email' => 2,
        'blocked_email_domains' => [
            '10minutemail.com',
            'guerrillamail.com',
            'mailinator.com',
            'tempmail.com',
            'temp-mail.org',
            'yopmail.com',
            'example.com',
            'test.com',
            'invalid.com',
        ],
        'blocked_website_domains' => [
            'example.com',
            'test.com',
            'localhost',
        ],
        'blocked_message_terms' => [
            'casino',
            'crypto giveaway',
            'viagra',
            'loan offer',
            'backlink package',
        ],
    ],
];
